# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import api_gateway_pb2 as api__gateway__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ApiGatewayStub(object):
    """*
    Сервис ApiGateway.
    Файл содержит protobuf схему данных для Эликонт-КС версий 2.X.X для обеспечения информационного обмена c микросервисом ApiGateway
    Дата: 21.10.2025
    (C) 2025 АО "ЭЛАРА". Все права защищены.

    АО "ЭЛАРА" предоставляет данный файл как открытый элемент программного продукта Эликонт-КС.
    Изменения данного файла могут нарушить работоспособность производного кода и связанных с ним пользовательских решений.
    АО "ЭЛАРА" не несёт ответсвенность за программный код, созданный сторонними разработчиками для обеспечения информационного обмена с Эликонт-КС и использующий данный файл.

    Лицензирование:
    Откройте раздел "Лицензия" в документации к продукту для получения подробной информации.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetConfig = channel.stream_unary(
                '/api_gateway.ApiGateway/SetConfig',
                request_serializer=api__gateway__pb2.FilePart.SerializeToString,
                response_deserializer=api__gateway__pb2.SetConfigResult.FromString,
                _registered_method=True)
        self.GetConfigState = channel.unary_unary(
                '/api_gateway.ApiGateway/GetConfigState',
                request_serializer=api__gateway__pb2.Empty.SerializeToString,
                response_deserializer=api__gateway__pb2.ConfigState.FromString,
                _registered_method=True)
        self.GetChannelsState = channel.unary_unary(
                '/api_gateway.ApiGateway/GetChannelsState',
                request_serializer=api__gateway__pb2.Empty.SerializeToString,
                response_deserializer=api__gateway__pb2.ChannelsState.FromString,
                _registered_method=True)
        self.TurnOnChannel = channel.unary_unary(
                '/api_gateway.ApiGateway/TurnOnChannel',
                request_serializer=api__gateway__pb2.Guid.SerializeToString,
                response_deserializer=api__gateway__pb2.Result.FromString,
                _registered_method=True)
        self.TurnOffChannel = channel.unary_unary(
                '/api_gateway.ApiGateway/TurnOffChannel',
                request_serializer=api__gateway__pb2.Guid.SerializeToString,
                response_deserializer=api__gateway__pb2.Result.FromString,
                _registered_method=True)
        self.GetCsInfo = channel.unary_unary(
                '/api_gateway.ApiGateway/GetCsInfo',
                request_serializer=api__gateway__pb2.Empty.SerializeToString,
                response_deserializer=api__gateway__pb2.CsInfo.FromString,
                _registered_method=True)
        self.GetLicenseState = channel.unary_unary(
                '/api_gateway.ApiGateway/GetLicenseState',
                request_serializer=api__gateway__pb2.Empty.SerializeToString,
                response_deserializer=api__gateway__pb2.LicenseState.FromString,
                _registered_method=True)
        self.SaveUserData = channel.stream_unary(
                '/api_gateway.ApiGateway/SaveUserData',
                request_serializer=api__gateway__pb2.FilePart.SerializeToString,
                response_deserializer=api__gateway__pb2.Result.FromString,
                _registered_method=True)
        self.LoadUserData = channel.unary_stream(
                '/api_gateway.ApiGateway/LoadUserData',
                request_serializer=api__gateway__pb2.Empty.SerializeToString,
                response_deserializer=api__gateway__pb2.FilePart.FromString,
                _registered_method=True)
        self.TraceOn = channel.unary_unary(
                '/api_gateway.ApiGateway/TraceOn',
                request_serializer=api__gateway__pb2.Guid.SerializeToString,
                response_deserializer=api__gateway__pb2.Result.FromString,
                _registered_method=True)
        self.TraceOff = channel.unary_unary(
                '/api_gateway.ApiGateway/TraceOff',
                request_serializer=api__gateway__pb2.Guid.SerializeToString,
                response_deserializer=api__gateway__pb2.Result.FromString,
                _registered_method=True)
        self.GetDatabasesState = channel.unary_unary(
                '/api_gateway.ApiGateway/GetDatabasesState',
                request_serializer=api__gateway__pb2.Empty.SerializeToString,
                response_deserializer=api__gateway__pb2.DatabasesState.FromString,
                _registered_method=True)
        self.GetLogMessages = channel.unary_unary(
                '/api_gateway.ApiGateway/GetLogMessages',
                request_serializer=api__gateway__pb2.Empty.SerializeToString,
                response_deserializer=api__gateway__pb2.Messages.FromString,
                _registered_method=True)
        self.GetTraceMessages = channel.unary_unary(
                '/api_gateway.ApiGateway/GetTraceMessages',
                request_serializer=api__gateway__pb2.Empty.SerializeToString,
                response_deserializer=api__gateway__pb2.TraceMessages.FromString,
                _registered_method=True)


class ApiGatewayServicer(object):
    """*
    Сервис ApiGateway.
    Файл содержит protobuf схему данных для Эликонт-КС версий 2.X.X для обеспечения информационного обмена c микросервисом ApiGateway
    Дата: 21.10.2025
    (C) 2025 АО "ЭЛАРА". Все права защищены.

    АО "ЭЛАРА" предоставляет данный файл как открытый элемент программного продукта Эликонт-КС.
    Изменения данного файла могут нарушить работоспособность производного кода и связанных с ним пользовательских решений.
    АО "ЭЛАРА" не несёт ответсвенность за программный код, созданный сторонними разработчиками для обеспечения информационного обмена с Эликонт-КС и использующий данный файл.

    Лицензирование:
    Откройте раздел "Лицензия" в документации к продукту для получения подробной информации.

    """

    def SetConfig(self, request_iterator, context):
        """*
        Задать конфигурацию КС.
        Отправляемый xml-файл должен соответствовать схеме для текущей версии коммуникационного сервера.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfigState(self, request, context):
        """*
        Получить состояние конфигурации коммуникационного сервера.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannelsState(self, request, context):
        """*
        Получить состояние каналов коммуникационного сервера.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TurnOnChannel(self, request, context):
        """*
        Включить канал с указанным GUID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TurnOffChannel(self, request, context):
        """*
        Выключить канал с указанным GUID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCsInfo(self, request, context):
        """*
        Получить информацию о коммуникационного сервера.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLicenseState(self, request, context):
        """*
        Получить состояние лицензии коммуникационного сервера.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveUserData(self, request_iterator, context):
        """*
        Сохранить пользовательские данные на коммуникационный сервер.

        [ВНИМАНИЕ]: Предыдущие пользовательские данные будут удалены.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadUserData(self, request, context):
        """*
        Получить пользовательские данные с коммуникационного сервера.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraceOn(self, request, context):
        """*
        Включить трассировку канала с указанным GUID.
        Если указанный канал не поддерживает трассировку, то сообщений трассировки от этого канала приходить не будет вне зависимости, включена ли трассировка на нём или нет.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraceOff(self, request, context):
        """*
        Выключить трассировку канала с указанным GUID.
        Если указанный канал не поддерживает трассировку, то сообщений трассировки от этого канала приходить не будет вне зависимости, включена ли трассировка на нём или нет.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatabasesState(self, request, context):
        """*
        Получить состояние баз данных, используемых коммуникационным сервером для архивации.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogMessages(self, request, context):
        """*
        Получить последние лог-сообщения коммуникационного сервера.
        Вызов этой функции возвращает накопленные сообщения относительно предыдущего вызова.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTraceMessages(self, request, context):
        """*
        Получить последние сообщения трассировки каналов коммуникационного сервера.
        Вызов этой функции возвращает накопленные сообщения относительно предыдущего вызова.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetConfig': grpc.stream_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=api__gateway__pb2.FilePart.FromString,
                    response_serializer=api__gateway__pb2.SetConfigResult.SerializeToString,
            ),
            'GetConfigState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfigState,
                    request_deserializer=api__gateway__pb2.Empty.FromString,
                    response_serializer=api__gateway__pb2.ConfigState.SerializeToString,
            ),
            'GetChannelsState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannelsState,
                    request_deserializer=api__gateway__pb2.Empty.FromString,
                    response_serializer=api__gateway__pb2.ChannelsState.SerializeToString,
            ),
            'TurnOnChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.TurnOnChannel,
                    request_deserializer=api__gateway__pb2.Guid.FromString,
                    response_serializer=api__gateway__pb2.Result.SerializeToString,
            ),
            'TurnOffChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.TurnOffChannel,
                    request_deserializer=api__gateway__pb2.Guid.FromString,
                    response_serializer=api__gateway__pb2.Result.SerializeToString,
            ),
            'GetCsInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCsInfo,
                    request_deserializer=api__gateway__pb2.Empty.FromString,
                    response_serializer=api__gateway__pb2.CsInfo.SerializeToString,
            ),
            'GetLicenseState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLicenseState,
                    request_deserializer=api__gateway__pb2.Empty.FromString,
                    response_serializer=api__gateway__pb2.LicenseState.SerializeToString,
            ),
            'SaveUserData': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveUserData,
                    request_deserializer=api__gateway__pb2.FilePart.FromString,
                    response_serializer=api__gateway__pb2.Result.SerializeToString,
            ),
            'LoadUserData': grpc.unary_stream_rpc_method_handler(
                    servicer.LoadUserData,
                    request_deserializer=api__gateway__pb2.Empty.FromString,
                    response_serializer=api__gateway__pb2.FilePart.SerializeToString,
            ),
            'TraceOn': grpc.unary_unary_rpc_method_handler(
                    servicer.TraceOn,
                    request_deserializer=api__gateway__pb2.Guid.FromString,
                    response_serializer=api__gateway__pb2.Result.SerializeToString,
            ),
            'TraceOff': grpc.unary_unary_rpc_method_handler(
                    servicer.TraceOff,
                    request_deserializer=api__gateway__pb2.Guid.FromString,
                    response_serializer=api__gateway__pb2.Result.SerializeToString,
            ),
            'GetDatabasesState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatabasesState,
                    request_deserializer=api__gateway__pb2.Empty.FromString,
                    response_serializer=api__gateway__pb2.DatabasesState.SerializeToString,
            ),
            'GetLogMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogMessages,
                    request_deserializer=api__gateway__pb2.Empty.FromString,
                    response_serializer=api__gateway__pb2.Messages.SerializeToString,
            ),
            'GetTraceMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTraceMessages,
                    request_deserializer=api__gateway__pb2.Empty.FromString,
                    response_serializer=api__gateway__pb2.TraceMessages.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api_gateway.ApiGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api_gateway.ApiGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApiGateway(object):
    """*
    Сервис ApiGateway.
    Файл содержит protobuf схему данных для Эликонт-КС версий 2.X.X для обеспечения информационного обмена c микросервисом ApiGateway
    Дата: 21.10.2025
    (C) 2025 АО "ЭЛАРА". Все права защищены.

    АО "ЭЛАРА" предоставляет данный файл как открытый элемент программного продукта Эликонт-КС.
    Изменения данного файла могут нарушить работоспособность производного кода и связанных с ним пользовательских решений.
    АО "ЭЛАРА" не несёт ответсвенность за программный код, созданный сторонними разработчиками для обеспечения информационного обмена с Эликонт-КС и использующий данный файл.

    Лицензирование:
    Откройте раздел "Лицензия" в документации к продукту для получения подробной информации.

    """

    @staticmethod
    def SetConfig(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/api_gateway.ApiGateway/SetConfig',
            api__gateway__pb2.FilePart.SerializeToString,
            api__gateway__pb2.SetConfigResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfigState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/GetConfigState',
            api__gateway__pb2.Empty.SerializeToString,
            api__gateway__pb2.ConfigState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannelsState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/GetChannelsState',
            api__gateway__pb2.Empty.SerializeToString,
            api__gateway__pb2.ChannelsState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TurnOnChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/TurnOnChannel',
            api__gateway__pb2.Guid.SerializeToString,
            api__gateway__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TurnOffChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/TurnOffChannel',
            api__gateway__pb2.Guid.SerializeToString,
            api__gateway__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/GetCsInfo',
            api__gateway__pb2.Empty.SerializeToString,
            api__gateway__pb2.CsInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLicenseState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/GetLicenseState',
            api__gateway__pb2.Empty.SerializeToString,
            api__gateway__pb2.LicenseState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveUserData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/api_gateway.ApiGateway/SaveUserData',
            api__gateway__pb2.FilePart.SerializeToString,
            api__gateway__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api_gateway.ApiGateway/LoadUserData',
            api__gateway__pb2.Empty.SerializeToString,
            api__gateway__pb2.FilePart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraceOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/TraceOn',
            api__gateway__pb2.Guid.SerializeToString,
            api__gateway__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraceOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/TraceOff',
            api__gateway__pb2.Guid.SerializeToString,
            api__gateway__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatabasesState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/GetDatabasesState',
            api__gateway__pb2.Empty.SerializeToString,
            api__gateway__pb2.DatabasesState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/GetLogMessages',
            api__gateway__pb2.Empty.SerializeToString,
            api__gateway__pb2.Messages.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTraceMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/GetTraceMessages',
            api__gateway__pb2.Empty.SerializeToString,
            api__gateway__pb2.TraceMessages.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
